### ISSUE TITLE
Building multiple jars 

### ISSUE THREAD

**Issue by ilbonte** [phoet/buildr-examples#2]
First of all thanks for these examples, you helped me a lot so far

I'm following your example for building multiple JARs (https://github.com/phoet/buildr-examples/blob/5ce199aa77cc78da477f8bf85bada81068973640/examples/packaging/multiple/buildfile)

Do you know if it's possible to build multiple jars but with different content all in the same project? For example I'd like to build a jar with the `src` and a jar with the `test`, all with the project (I mean in the same `define`)

Something like (it's "pseudo code")
```
define "multiple", :version=>"1.0.0" do
   test.with JMOCK
   compile.with XSTREAM
   package(:jar) #<--- jar for src code

  compile.with JMOCK
  package(:file => _(:target, 'my_tests.jar'))  #j<-- jar for tests
end
```

**Comment by phoet** [comment]
sorry, I haven't used buildr for years. if you find out something about
that topic, feel free to provide an example.

Davide Bontempelli <notifications@github.com> schrieb am Fr., 21. Apr.
2017, 18:03:
